Most of the steps to get a static Linux build working.
Deltares/MeshKernel pull request #114
Opened 2021-07-27 16:14 UTC by evetion

In `scripts/compile_deps.sh` there's a commented out section which compiles meshkernel, with a `vim build/CMakeCache.txt`.

In there I manually had to set:
`OpenMP_CXX_FLAGS:STRING=-fopenmp` -> `OpenMP_CXX_FLAGS:STRING=-fopenmp -static`
`OpenMP_C_FLAGS:STRING=-fopenmp` -> `OpenMP_C_FLAGS:STRING=-fopenmp -static`
`OpenMP_gomp_LIBRARY:FILEPATH=/some/path/libgomp.so` -> `OpenMP_gomp_LIBRARY:FILEPATH=/some/path/libgomp.a`

Profiling/coverage information is still in the Linux builds, should be nicely removed on a Release build.

2023-02-22 09:15 UTC, ahmad-el-sayed requested changes

2023-02-24 13:07 UTC, lucacarniato commented on scripts/compile_deps.sh
> +# add gcc
I removed the commented block

2023-02-24 13:10 UTC, lucacarniato commented on CMakeLists.txt
> +else()
i will rebase with branch feature/GRIDEDIT-484_remove_boost_system_and_filesystem_dependencies

2023-02-24 13:11 UTC, lucacarniato commented on scripts/compile_deps.sh
> +#rm -rf gcc-9.3.0.tar.gz
this part of the code is removed

2023-02-24 13:29 UTC, lucacarniato commented on scripts/compile_deps.sh
> +# add boost
done

2023-03-21 08:59 UTC, lucacarniato commented
Now linux build is working in master

2023-03-21 08:59 UTC, closed without merging