refinement bug
Deltares/MeshKernel pull request #170
Opened 2023-06-06 11:11 UTC by lucacarniato

2023-06-12 15:18 UTC, ahmad-el-sayed commented
@lucacarniato feature name includes GRIDEDIT-566. Issue is GRIDEDIT-556. Please remember this when you format the message of the squashed commits.

2023-06-13 09:03 UTC, ahmad-el-sayed requested changes

2023-06-13 11:17 UTC, lucacarniato commented on libs/MeshKernel/include/MeshKernel/MeshRefinement.hpp
> +        /// @brief Computes refinement masks (compute_jarefine_poly)
I agree with putting this info in a comment. i will create a task for this

2023-06-13 11:56 UTC, lucacarniato commented on libs/MeshKernel/src/MeshRefinement.cpp
> +            const auto tolerance = 1e-4 * std::max(firstEdgeSquaredLength, secondEdgeSquaredLength);
changed to minConnectionDistance

2023-06-13 12:45 UTC, lucacarniato commented on libs/MeshKernel/src/CurvilinearGrid/CurvilinearGridCreateUniform.cpp
> +    constexpr double latitudeCloseToPoles = 88.0;
I wrote some comments, for later reference.

2023-06-13 13:04 UTC, lucacarniato commented on libs/MeshKernel/src/MeshRefinement.cpp
>      if (m_refinementType == RefinementType::RefinementLevels)
i am default initializing the refinement type in meshrefinement.hpp 

RefinementType m_refinementType = RefinementType::WaveCourant; ///< The type of refinement to use

2023-06-13 13:22 UTC, ahmad-el-sayed approved these changes

2023-06-13 13:22 UTC, merged