feature/GRIDEDIT-539_error_handling_and_logging
Deltares/MeshKernel pull request #221
Opened 2023-09-12 14:03 UTC by ahmad-el-sayed

2023-09-25 12:54 UTC, ScottWillcox approved these changes

2023-09-26 15:57 UTC, lucacarniato requested changes

2023-09-26 15:57 UTC, lucacarniato commented on libs/MeshKernelApi/tests/src/ErrorHandlingTests.cpp
> +    this->MakeUniformCurvilinearGrid(3, 3);
do you need this pointer here?

2023-09-28 11:50 UTC, lucacarniato approved these changes

2023-09-28 13:56 UTC, merged