Append MeshKernel NuGet release package name with build number
Deltares/MeshKernel pull request #245
Opened 2023-10-19 12:59 UTC by ahmad-el-sayed

2023-10-23 10:19 UTC, ahmad-el-sayed commented on package/Deltares.MeshKernel.Devel.nuspec.in
@ScottWillcox  This input config is unused inTC. Shallwe remove it?

2023-10-23 14:04 UTC, ScottWillcox commented on package/Deltares.MeshKernel.Devel.nuspec.in
> +        <version>@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@-dev.@VERSION_SUFFIX@</version>
I would do something like: major.minor.patch.versionsuffix-dev

2023-10-23 14:07 UTC, ScottWillcox requested changes
I would change the way the version is build. adding the -dev as last. After the build number.

2023-10-24 07:26 UTC, ScottWillcox approved these changes

2023-10-24 09:59 UTC, merged