Feature/gridedit 778 casulli derefinement
Deltares/MeshKernel pull request #329
Opened 2024-05-02 14:08 UTC by BillSenior

2024-05-22 13:47 UTC, lucacarniato requested changes

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/include/MeshKernel/CasulliDeRefinement.hpp
> +        UInt FindCommonNode(const Mesh2D& mesh, const UInt edgeId1, const UInt edgeId2) const;
Is this function already implemented elsewhere?
meshkernel::UInt Mesh::FindCommonNode(UInt firstEdgeIndex, UInt secondEdgeIndex) const

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +        if (std::ranges::find(connected, neighbouringElementId) == connected.end())
do you need this check, std::ranges::find for every added face? it looks like you are simply looping over the edges of the faces. the added faces should not be the same if there are no hanging nodes

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +            for (UInt k = 0; k < mesh.m_edgesNumFaces[edgeId]; ++k)
can you skip this loop and use a single if? m_edgesNumFaces can be at maximum 2

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +        if (ElementIsSeed(mesh, nodeTypes, elementId))
maybe store the value of this function for each element?

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +
nMax ,maxIterationCount as const initialized class members?

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +        if (nodeTypes[nodeId] == 2 || nodeTypes[nodeId] == 4)
can we use an enum for nodeTypes? difficult to say what 2 and 4 are

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +                        // Error: No node found
do we need to throw an exception here?

2024-05-22 13:47 UTC, lucacarniato commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +meshkernel::UInt meshkernel::CasulliDeRefinement::FindCommonNode(const Mesh2D& mesh, const UInt edgeId1, const UInt edgeId2) const
use what is already avail in mk

2024-05-22 14:23 UTC, BillSenior commented on libs/MeshKernel/src/CasulliDeRefinement.cpp
> +meshkernel::UInt meshkernel::CasulliDeRefinement::FindCommonNode(const Mesh2D& mesh, const UInt edgeId1, const UInt edgeId2) const
Removed

2024-05-22 14:23 UTC, BillSenior commented on libs/MeshKernel/include/MeshKernel/CasulliDeRefinement.hpp
> +        void AddElementToList(const Mesh& mesh, const std::vector<UInt>& frontList, std::vector<UInt>& frontListCopy, const UInt kNew) const;
Changed to elementId

2024-05-22 14:24 UTC, BillSenior commented on libs/MeshKernel/include/MeshKernel/Mesh.hpp
> +inline meshkernel::Edge& meshkernel::Mesh::GetEdge(const UInt index)
It is a little bit dangerous, because it bypasses the undo functionality

2024-05-27 16:03 UTC, lucacarniato approved these changes

2024-05-27 16:16 UTC, BillSenior commented on libs/MeshKernelApi/include/MeshKernelApi/MeshKernel.hpp
> +        MKERNEL_API int mkernel_mesh2d_casulli_derefinement_elements(int meshKernelId, GeometryList* elements);
Removed the pointers.
Elements is passed back to the front end for plotting of the element centres

2024-05-27 16:17 UTC, BillSenior commented on libs/MeshKernelApi/include/MeshKernelApi/MeshKernel.hpp
> +        MKERNEL_API int mkernel_mesh2d_casulli_derefinement(int meshKernelId);
the element extension means that it computed only the element centres of the elements that are to be in the de-refinement. In interactor they are highlighted with a dot at the centre of the element

2024-05-30 08:12 UTC, merged