GRIDEDIT-1244 Split row/column for unstructured meshes
Deltares/MeshKernel pull request #345
Opened 2024-06-24 16:08 UTC by BillSenior

2024-07-10 10:49 UTC, lucacarniato requested changes

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/include/MeshKernel/SplitRowColumnOfMesh.hpp
> +        bool MayBeSplit(const Mesh2D& mesh, const UInt edgeId) const;
I would rename it CanBeSplit?

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/src/Mesh.cpp
> +    // TODO use Operations::FindIndex when curvilinear grid from splines has been added to master
remove todo?

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/src/SplitRowColumnOfMesh.cpp
> +    UInt previousElementId = edgeFace[0] + edgeFace[1] - elementId;
use const

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/src/SplitRowColumnOfMesh.cpp
> +            // There is no elememnt on the other side of the edge.
elememnt => element

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/src/SplitRowColumnOfMesh.cpp
> +    const UInt initialNumberOfElements = static_cast<UInt>(std::sqrt(static_cast<double>(mesh.GetNumNodes())));
GetNumFaces?

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/src/SplitRowColumnOfMesh.cpp
> +    const UInt initialNumberOfElements = static_cast<UInt>(std::sqrt(static_cast<double>(mesh.GetNumNodes())));
initialNumberOfFaces?

2024-07-10 10:49 UTC, lucacarniato commented on libs/MeshKernel/src/SplitRowColumnOfMesh.cpp
> +    for (UInt i = 0; i < 2; ++i)
create a function and call it twice? this could reduce the cyclomatic complexity a bit

2024-07-10 10:58 UTC, BillSenior commented on libs/MeshKernelApi/include/MeshKernelApi/MeshKernel.hpp
> +        /// @param[in] meshKernelId The id of the mesh state
Correct comment

2024-07-11 16:10 UTC, lucacarniato approved these changes

2024-07-15 07:54 UTC, merged